### ISSUE TITLE
Add new sections for DataLayer and WalletConnect

### ISSUE THREAD

**Issue by SlowestTimelord** [Chia-Network/chialinks#37]
There's been new development happening with dApps around WalletConnect and https://github.com/MichaelTaylor3D has been pushing DataLayer tools out like a firehose. Probably warrants new sections/sub-sections dedicated to these topics.

**Comment by BrandtH22** [comment]
Adding links here for inclusion (note this might not capture everything that is currently available):

WalletConnect:
Chia Official Example dApp- https://github.com/Chia-Network/walletconnect-rpcs-dapp
Chia Official Example dApp (deprecated)- https://github.com/Chia-Network/chia-wallet-connect-dapp-test
Open Market Dev Clup dApp example (Gaerex)- https://github.com/Open-Market-Dev-Club/chia-walletconnect
.net dApp implementation (blackcode)- https://github.com/Blackcode/ChiaWalletConnect.dotnet
angular dApp implementation (greimela)- https://github.com/greimela/walletconnect-chia-angular
DID message signing example (mikehw)- https://github.com/mikehw/chia-did-message-demo

DataLayer:
Chia Official cadt API- https://github.com/Chia-Network/cadt
Chia Official cadt UI- https://github.com/Chia-Network/cadt-ui
Tail Database app(freddiecoleman)- https://github.com/Tail-Database/tail-database-app
Tail Database API(freddiecoleman)- https://github.com/Tail-Database/tail-database-api
Tail Database client(freddiecoleman)- https://github.com/Tail-Database/tail-database-client
DataPlayer datalayer wrapper(cripsisxyz)- https://github.com/cripsisxyz/chia-dataplayer
Sprout CLI datalayer wrapper(MichaelTaylor3D)- https://github.com/MichaelTaylor3D/ChiaSproutCli
ChangeList Chunks js datalayer wrapper(MichaelTaylor3D)- https://github.com/MichaelTaylor3D/ChiaChangeListChunks
ChangeList Generator datalayer wrapper(MichaelTaylor3D)- https://github.com/MichaelTaylor3D/chia-changelist-generator
Datalayer kv cache(MichaelTaylor3D)- https://github.com/MichaelTaylor3D/chia-datalayer-kv-cache
Datalayer update notifier(MichaelTaylor3D)- https://github.com/MichaelTaylor3D/chia-datalayer-update-notifier
databin.store T3 dApp example(JonathanLangton1)- https://github.com/JonathanLangton1/databin.store
