### ISSUE TITLE
Add a page of known donation addresses

### ISSUE THREAD

**Issue by SlowestTimelord** [Chia-Network/chialinks#6]
Have a central place to find donation addresses of various ecosystem projects and charities.

Examples:
- Charity: Marmot Recovery Fund
- Ecosystem project: Spacescan.io

Proposed guidelines:
- Project should be a useful part of the ecosystem
- Charities and non-profits should be registered and well-established
- Will only list xch addresses directly owned by the project/charity -- not held by someone else in trust.
- PR reviews on updates to this page require reviewer's due diligence

Additional idea:
- Use a tool like splitxch.com to set up a predetermined split amongst multiple projects so users can simply donate to a single address.
- Can encourage farmers to set their payout address to a donation address as well. Either their block reward, or set up separate PlotNFTs altogether to dedicate some plots to help the ecosystem.

**Comment by sargonas** [comment]
Love this idea! 
I can grab the marmot recovery fund address right now. It is `xch120ywvwahucfptkeuzzdpdz5v0nnarq5vgw94g247jd5vswkn7rls35y2gc`
